In [1]:
import numpy as np 
dataset_filename = "affinity_dataset.txt" 
X = np.loadtxt(dataset_filename) 

In [2]:
print(X[:5]) 

[[0. 0. 1. 1. 0.]
 [1. 1. 0. 0. 0.]
 [1. 0. 0. 1. 1.]
 [0. 1. 1. 0. 1.]
 [0. 1. 0. 0. 0.]]


In [6]:
n_samples, n_features = X.shape

In [11]:
from collections import defaultdict
# 上面"买了苹果又买香蕉"是一种情况，现在把所有可能的情况都做一遍
valid_rules = defaultdict(int)
invalid_rules = defaultdict(int)
num_occurences = defaultdict(int)

for sample in X:
    for premise in range(n_features):
        if sample[premise] == 0: continue
        # 先买premise，premise代表一种食物，记做X
        num_occurences[premise] += 1
        for conclusion in range(n_features):
            if premise == conclusion:  
                continue # 跳过买X又买X的情况
            if sample[conclusion] == 1: # 又买了conclusion，conclusion代表一种食物，记做Y
                valid_rules[(premise, conclusion)] += 1 # 买X买Y
            else: 
                invalid_rules[(premise, conclusion)] += 1 # 买X没买Y
support = valid_rules
confidence = defaultdict(float)
for premise, conclusion in valid_rules.keys():
    confidence[(premise, conclusion)] = valid_rules[(premise, conclusion)] / num_occurences[premise]

In [12]:
def print_rule(premise, conclusion, support, confidence, features):
    premise_name = features[premise]
    conclusion_name = features[conclusion]
    print("Rule: 买了{0}，又买{1}".format(premise_name, conclusion_name))
    print(" - 置信度Confidence: {0:.3f}".format(confidence[(premise, conclusion)]))
    print(" - 支持度Support: {0}".format(support[(premise, conclusion)]))
    print("")

In [14]:
features = ["bread", "milk", "cheese", "apples", "bananas"]

In [15]:
premise = 1
conclusion = 3
print_rule(premise, conclusion, support, confidence, features)

Rule: 买了milk，又买apples
 - 置信度Confidence: 0.184
 - 支持度Support: 9



In [16]:
from operator import itemgetter 
sorted_support = sorted(support.items(), key=itemgetter(1), reverse=True) 
for index in range(5): 
     print("Rule #{0}".format(index + 1)) 
     (premise, conclusion) = sorted_support[index][0] 
     print_rule(premise, conclusion, support, confidence, features) 

Rule #1
Rule: 买了cheese，又买apples
 - 置信度Confidence: 0.553
 - 支持度Support: 26

Rule #2
Rule: 买了apples，又买cheese
 - 置信度Confidence: 0.667
 - 支持度Support: 26

Rule #3
Rule: 买了cheese，又买bananas
 - 置信度Confidence: 0.532
 - 支持度Support: 25

Rule #4
Rule: 买了bananas，又买cheese
 - 置信度Confidence: 0.463
 - 支持度Support: 25

Rule #5
Rule: 买了apples，又买bananas
 - 置信度Confidence: 0.590
 - 支持度Support: 23

